import { rotationNone, rotationL1, rotationD1, rotationU1 } from './rotations'

export const createPieceT = (id, x, sprite, status) => [
  {
    id,
    initialX: x + 1,
    initialY: 0,
    x: x + 1,
    y: 0,
    moveX: 0,
    moveY: 0,
    moveUpdate: false,
    status,
    gravityCounter: 0,
    sprite: sprite === '0' ? '0' : sprite,
    rotation: rotationNone(),
  },
  {
    id,
    initialX: x,
    initialY: 0,
    x,
    y: 0,
    moveX: 0,
    moveY: 0,
    moveUpdate: false,
    status,
    gravityCounter: 0,
    sprite: sprite === '0' ? '1' : sprite,
    rotation: rotationU1(),
  },
  {
    id,
    initialX: x + 2,
    initialY: 0,
    x: x + 2,
    y: 0,
    moveX: 0,
    moveY: 0,
    moveUpdate: false,
    status,
    gravityCounter: 0,
    sprite: sprite === '0' ? '2' : sprite,
    rotation: rotationD1(),
  },
  {
    id,
    initialX: x + 1,
    initialY: 1,
    x: x + 1,
    y: 1,
    moveX: 0,
    moveY: 0,
    moveUpdate: false,
    status,
    gravityCounter: 0,
    sprite: sprite === '0' ? '3' : sprite,
    rotation: rotationL1(),
  },
]
