import { 
  rotationNone,  
} from './rotations'

export const createPieceBox = (id, x, sprite, status) => [
  {
    id,
    initialX: x,
    initialY: 0,
    x,
    y: 0,
    moveX: 0,
    moveY: 0,
    moveUpdate: false,
    status,
    gravityCounter: 0,
    sprite: sprite === '0' ? '0' : sprite,  
    rotation: rotationNone(),
  },
  {
    id,
    initialX: x + 1,
    initialY: 0,
    x: x + 1,
    y: 0,
    moveX: 0,
    moveY: 0,
    moveUpdate: false,
    status,
    gravityCounter: 0,
    sprite: sprite === '0' ? '1' : sprite,  
    rotation: rotationNone(1,0),
  },
  {
    id,
    initialX: x,
    initialY: 1,
    x,
    y: 1,
    moveX: 0,
    moveY: 0,
    moveUpdate: false,
    status,
    gravityCounter: 0,
    sprite: sprite === '0' ? '2' : sprite,  
    rotation: rotationNone(0,1),
  },
  {
    id,
    initialX: x + 1,
    initialY: 1,
    x: x+1,
    y: 1,
    moveX: 0,
    moveY: 0,
    moveUpdate: false,
    status,
    gravityCounter: 0,
    sprite: sprite === '0' ? '3' : sprite,  
    rotation: rotationNone(1,1),
  },
]
